validation of package name

diff --git a/pkg_util b/pkg_util
--- a/pkg_util
+++ b/pkg_util
@@ -4,13 +4,38 @@ set -eu
 
 lapt_dir=$(dirname $(readlink -f $0))
 ldpkg=$lapt_dir/ldpkg
+log=$lapt_dir/lapt_log
+
+source $lapt_dir/color_palette
+
+function pu_validate() {
+    local pkg_str=$1
+    local type=$2
+    local re_name='[a-z0-9][a-z0-9+.-]*'
+    local re_ver='\(([^|]*)\)'
+    # ↑下で ? をつけるので grouping しておく
+    # ↑version 番号は | だけ除いておいて誤魔化す
+    local re_name_ver=" *$re_name *$re_ver\? *"
+    case "$type" in
+        name) re="^$re_name$";;
+        version) re="^$re_name_ver$";;
+        union) re="^$re_name_ver\\(| *$re_name_ver *\\)*$";;
+        *) $log "${RED}[Error]${ENDCOLOR} Invalid type"
+           exit 1;;
+    esac
+    echo "$pkg_str" |
+        grep "$re" >/dev/null 2>/dev/null
+}
 
 function pu_extract_pkg_name() {
     # Usage:
     #   pu_extract_pkg_name libtiff5
     #   pu_extract_pkg_name " libtiff5 (= 4.0.9-5ubuntu0.3) "
     local pkg_name_with_version=$1
-    # TODO: "|" が含まれてたらエラーを吐く
+    if ! pu_validate "$pkg_name_with_version" version; then
+        $log "${RED}[Error]${ENDCOLOR} Invalid package name in pu_extract_pkg_name"
+        exit 1
+    fi
     local pkg_name=$(echo "$pkg_name_with_version" |
                              sed -e 's/(.*)//' |
                              sed -e 's/^ *//' |
